name: Notify Discord on develop push

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"🚀 Nuevo push a la rama **main** del repo **${{ github.repository }}** por **${{ github.actor }}**.
👉 [Ver commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
📄 Mensaje: *${{ github.event.head_commit.message }}*
🔑 SHA: \`${{ github.sha }}\`\",
            \"username\": \"GitHub Bot\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
