name: Notify Discord on develop push

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🚀 Nuevo push a **develop** en **${{ github.repository }}** por **${{ github.actor }}**. 📄 *${{ github.event.head_commit.message }}* 🔑 \`${{ github.sha }}\`\", \"username\": \"GitHub Bot\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
